#!/usr/bin/env bash

source create_passwd

cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: $(hostname)-secret
  namespace: $POD_NAMESPACE
  labels:
    job: $(hostname)
    app.kubernetes.io/managed-by: open-ondemand
data:
  password: $(echo -n "$PASSWORD" | base64 )
EOF
